### ISSUE TITLE
대기 서버 구상 초안

### ISSUE THREAD

**Issue by jaejeong1** [f-lab-edu/ticket-seller#10]
![image](https://user-images.githubusercontent.com/89735640/217386950-ba8d3b9e-0a86-46fe-a094-a9bb042aaeb4.png)
#9 의 1단계 : 공연 선택 시 대기 순번 제공에 대한 구상 초안

기술적 고려사항
1. 대기 서버와 예약 서버 Scale out을 어떤 기준과 방법으로 해야할지?
2. 예약 풀 자리가 났을때 대기 서버로의 분배는 어떻게 할지? 
3. 예약 풀이 다 찼다의 기준은 어떻게 할지?
4. 대기 순번은 어떻게 제공할지?
5. 공연 좌석 예약 특성 상 많은 Write가 동시에 발생할텐데 어떻게 처리할건지?

**Comment by jaejeong1** [comment]
1. 대기 서버와 예약 서버 Scale out을 어떤 기준과 방법으로 해야할지?
=> 대기 서버는 단순히 예약 서버로 넘겨줄 큐에 넣어주는 역할만 하는 방식으로 구상해보자

2. 예약 풀 자리가 났을때 대기 서버로의 분배는 어떻게 할지?
=> 1번 방식으로 하면 분배가 필요없어짐

3. 예약 풀이 다 찼다의 기준은 어떻게 할지?
=> 기준은 여러가지가 될 수 있으나 1차적으로 시간당 100~200명 같은 기본 정책으로 접근해보자

4. 대기 순번은 어떻게 제공할지?
=> 예약이 완료된 건마다 예약 서버에서 큐를 감소시킴. 서비스 특성 상 1의 자리까지 정확한 순번 제공은 필요하지 않으니, 큐의 사이즈를 이용해 대기 순번으로 제공해줘도 될 것. 웹소켓을 사용하지 않고 구현하는 방법도 찾아보자

5. 공연 좌석 예약 특성 상 많은 Write가 동시에 발생할텐데 어떻게 처리할건지?
=> DB 샤딩 측면으로 접근해 방법을 찾아보자

**Comment by heeve1** [comment]
프론트와 서버의 연결부분은 우선 풀링으로 구현하고 추후 웹소켓으로 전환하는 것도 나쁘지 않을 것 같다는 생각도 드네요~
