### ISSUE TITLE
메시지 큐 조사 및 대기 서버 아키텍처에 필요한 요구사항 정리

### ISSUE THREAD

**Issue by jaejeong1** [f-lab-edu/ticket-seller#13]
### 메시지 큐
- 응용 프로그램 또는 서비스 간의 비동기 통신을 활성화하여 분리하는 데 사용되는 미들웨어

#### 주요 사용 사례
1. 대량 메시지 처리: 애플리케이션이 대량의 메시지 또는 요청을 처리해야 하는 경우 메시지 대기열을 사용하면 처리 부담을 줄이고 애플리케이션의 여러 인스턴스에 로드를 분산하는 데 도움이 될 수 있다.

2. 비동기 처리: 애플리케이션이 작업을 비동기적으로 수행해야 하는 경우 메시지 큐를 사용하여 메시지 또는 작업 처리를 관리할 수 있으므로 애플리케이션이 응답을 차단하거나 기다리지 않고 다른 요청을 계속 처리할 수 있다.

3. 크로스 플랫폼 통합: 서로 다른 언어로 작성되었거나 서로 다른 기술을 사용하는 여러 시스템 또는 애플리케이션을 통합할 때 메시지 큐는 통신을 위한 표준 인터페이스를 제공하여 서로 다른 구성 요소가 느슨하게 결합된 방식으로 메시지를 통신하고 교환할 수 있도록 한다.

4. 신뢰성: 애플리케이션이 메시지가 안정적으로 전달 및 처리되도록 해야 하는 경우 메시지 큐는 메시지 지속성, 재시도 메커니즘 및 메시지가 손실되거나 삭제되지 않도록 하는 오류 처리와 같은 기능을 제공할 수 있다.

5. 확장 및 가용성: 증가하는 수요를 처리하기 위해 애플리케이션을 수평으로 확장해야 하는 경우 메시지 대기열을 사용하면 처리 부하를 여러 인스턴스에 분산하고 내결함성 및 고가용성을 제공하는 데 도움이 될 수 있다.

요약하면 메시지 큐는 애플리케이션이 대용량 메시지 처리를 처리하고, 작업을 비동기식으로 수행하고, 다른 시스템과 통합하고, 안정성을 보장하고, 확장하여 고가용성을 제공해야 하는 경우 유용할 수 있다. 
메시지 큐를 사용함으로써 응용 프로그램은 구성 요소를 분리하고, 보다 효율적인 방식으로 메시지 처리를 관리하여 더 나은 성능, 안정성 및 확장성을 얻을 수 있다.

### 대기 서버 아키텍처에서 기술적 요구 사항
1. 대량 메시지 처리
- 공연 오픈 시 동시에 많은 유저들이 대기열 진입, 대용량 트래픽 발생
2. 비동기 처리
- 대기열에서 넘어간 예약 요청이 언제 끝날지 정확히 알 수 없어 비동기 처리 필요
3. 신뢰성
- 대기열이 죽으면 공연 예약 서비스에 큰 문제가 발생. 높은 신뢰성 필요
4. 확장 및 고가용성
- 수평 확장이 필요한 대기 및 예약(비동기 작업) 특성에 따라 확장성 및 고가용성 필요

**Comment by heeve1** [comment]
"대기열에서 넘어간 예약 요청이 언제 끝날지 정확히 알 수 없어 비동기 처리 필요"
라고 언급 주신 2번은 비동기 처리로 인한 결과로 볼수도 있는 문구인것 같아요.
비동기를 사용하는 니즈는 여러가지가 있을 것 같은데요
* 성능
* 스케일 아웃 용이성(통신을 하는 서버가 느슨하게 연결되기 떄문에)
* 장애로 인한 유실 대비(큐만 안죽는다면 재시도 가능)
* 등등~

**Comment by jaejeong1** [comment]
네, 제가 2번에서 의도한 바는 말씀주신 사항 중 "성능"과 "장애로 인한 유실 대비"였습니다.
스케일 아웃 용이성 또한 함께 비동기 사용 니즈로 알아두도록 하겠습니다! 감사합니다 :)
