### ISSUE TITLE
대기 서버 구상 - (4), 입장권 검증 로직 추가

### ISSUE THREAD

**Issue by jaejeong1** [f-lab-edu/ticket-seller#16]
![image](https://user-images.githubusercontent.com/89735640/221875484-f87d178f-7a10-44b3-a93c-9606c14e5c76.png)

1. 입장권 검증 로직 추가
2. 대기열 폴링이 끝나면 서버에서 포워딩 하지않고, 클라이언트(유저)가 발급된 입장권(JWT 포함)을 들고 예약 요청 하도록 로직 수정
---2차 수정 추가 사항---
3. Cutoff 기준 제거, 얼마나 진입 허용 시킬지에 대한 건은 대기 서버에서 자체 기준에 따라 결정해 예약 서버는 관련없도록 변경
4. JWT Expired Time은 발급된 입장권의 재사용을 막기 위한 검증 수단으로 사용
5. 예약 완료 또는 유저가 이탈하면 해당 대기열은 완료처리해 대기 순번 계산 및 조회 시 사용

**Comment by heeve1** [comment]
흠 어떻게 스펙을 잡을지에 따라 다를 것 같기는한데, JWT를 사용하게 된다면 CUTOFF 조건은 없어도 되지 않을까요? (SIGNED 되었는지와 EXPIRESAT만 살펴보는 것)

**Comment by jaejeong1** [comment]
> 흠 어떻게 스펙을 잡을지에 따라 다를 것 같기는한데, JWT를 사용하게 된다면 CUTOFF 조건은 없어도 되지 않을까요? (SIGNED 되었는지와 EXPIRESAT만 살펴보는 것)

넵! 진입 허용 기준이 JWT와 Cutoff 2가지로 중복되어 있던 오류를 수정하고, JWT Expired Time의 활용 방법을 입장권 검증으로 변경해서 다시 수정해보았습니다.
 한번 확인해주시면 감사하겠습니다!!

**Comment by heeve1** [comment]
1. 대기서버와 예약서버 사이의 연결은 어떤 역할이려나요? 그때 말씀 드렸던 예약서버가 대기서버가 살아있는지 헬스를 체크하는 역할은 아닌 것 같아서요~ (메시지 큐 포함)
2. JWT 발급기준 확인은 왠지 대기 표 발급 오퍼레이션에서 체크하지 않으려나용?
3. 표에서 파란색 네모가 의미하는 바가 조금씩 다른 컴포넌트가 혼재되어 있어 보기에 딱 직관적이지 않은 것 같습니다.
    3-1.  대기 서버, 예약 서버는 단어 그대로 컴포넌트를 의미하는 것 같구요
    3-2.  입장권 발급, 대기표 발급, 대기순번 조회는 특정 오퍼레이션을 의미하는 것 같아서요.

-> 3-1번은 현재 순서도 포맷으로 두고 3-2번은 시퀀스 다이어 그램으로 변경해보는건 어떨까 싶네용(물론 다른 적합한 다이어그램으로 변경으로도 좋을 것 같습니다)

**Comment by jaejeong1** [comment]
> 1. 대기서버와 예약서버 사이의 연결은 어떤 역할이려나요? 그때 말씀 드렸던 예약서버가 대기서버가 살아있는지 헬스를 체크하는 역할은 아닌 것 같아서요~ (메시지 큐 포함)
> 2. JWT 발급기준 확인은 왠지 대기 표 발급 오퍼레이션에서 체크하지 않으려나용?
> 3. 표에서 파란색 네모가 의미하는 바가 조금씩 다른 컴포넌트가 혼재되어 있어 보기에 딱 직관적이지 않은 것 같습니다.
>    3-1.  대기 서버, 예약 서버는 단어 그대로 컴포넌트를 의미하는 것 같구요
>    3-2.  입장권 발급, 대기표 발급, 대기순번 조회는 특정 오퍼레이션을 의미하는 것 같아서요.
> 
> -> 3-1번은 현재 순서도 포맷으로 두고 3-2번은 시퀀스 다이어 그램으로 변경해보는건 어떨까 싶네용(물론 다른 적합한 다이어그램으로 변경으로도 좋을 것 같습니다)

1. 의도한 바는 예약 서버에서 처리가 끝나, 다음 대기열을 넘겨받아야 할 때, 대기열에 피드백을 주고, 다음 대기열을 전달받아오는 것이었습니다.
2. 내용 작성이 잘못된 부분이 있어 이미지 수정해 다시 업로드하였습니다!
3. 네, 점점 내용이 많아지다보니 직관적이지 않고, 복잡해진 것 같습니다. 분리해서 작성해보겠습니다~!
