### ISSUE TITLE
대기 서버 구상 (5) - 시퀀스 다이어그램 추가, 일부 로직 수정

### ISSUE THREAD

**Issue by jaejeong1** [f-lab-edu/ticket-seller#17]
대기 서버 구상 (4)까지 발생했던 기술적 미해결 사항

1. 대기 순번 계산
- Redis의 SortedSet을 사용해 유저들을 대기 순번 기준으로 정렬해 큐처럼 사용
- 현재 순위(순번) 조회가 많이 발생할 것으로 예상되어, 해당 작업에 O(N)이 발생하는 큐 대신 SortedSet 선정
- 현재 순위 조회 : O(logN), ZRANK
- 전체 대기자 수 : O(1), ZCARD

2. 예약 완료 또는 예약 중 이탈 여부 판단
- JWT는 대기 ~ 예약 입장까지만 사용하고, 입장권 검증이 완료되면 예약 과정은 웹소켓 세션 연결해 진행
- JWT로 관리 했을 때 계산하기 어려운 예약 중도 이탈 시 카운트, 현재 예약 중인 유저 수를 쉽게 구할 수 있음
- 현재 예약 진행 중인 실제 유저 수를 알 수 있으므로, 보다 정확한 트래픽 제어 가능

3. 유저 ~ 대기 ~ 예약 간 동작 순서가 현 구조도에서 시인성이 떨어짐
- 시퀀스 다이어그램 추가
![에프랩 시퀀스다이어그램](https://user-images.githubusercontent.com/89735640/222881348-ee04b653-4086-4507-af92-53f603a36fbd.png)

4. Spring Batch 사용해 주기적으로 현재 예약 중 Capa 확인 및 대기 서버 알림, 신규 예약 입장 요청 진행

5. 최종 변경된 구조도
![image](https://user-images.githubusercontent.com/89735640/222907638-77b529ee-c9e2-4020-a66e-a9c7e2f5474a.png)

**Comment by heeve1** [comment]
좋습니다. 전체적인 방향은 구현을 통해서 좀더 보완해보면 괜찮을 것 같아요~
추후 시퀀스 다이어 그램은 좀더 상세한 알고리즘으로, 구조도는 전체 컴포넌트를 한눈에 볼 수 있는 뷰로 개선되면 더욱 좋을 것 같습니다.
